.TH ARPTABLES-LEGACY-SAVE 8 "May 08, 2008" "" ""
.\"
.\" Man page written by Jochen Friedrich <jochen@scram.de>
.\" It is based on the iptables-save man page.
.\"
.\"	This program is free software; you can redistribute it and/or modify
.\"	it under the terms of the GNU General Public License as published by
.\"	the Free Software Foundation; either version 2 of the License, or
.\"	(at your option) any later version.
.\"
.\"	This program is distributed in the hope that it will be useful,
.\"	but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"	GNU General Public License for more details.
.\"
.\"	You should have received a copy of the GNU General Public License
.\"	along with this program; if not, write to the Free Software
.\"	Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
.\"
.\"
.SH NAME
arptables-legacy-save \- Save ARP Tables
.SH SYNOPSIS
.BR "arptables-legacy-save "
.br
.SH DESCRIPTION
.PP
.B arptables-legacy-save
is used to dump the contents of an ARP Table in easily parseable format
to STDOUT. Use I/O-redirection provided by your shell to write to a file.
.SH BUGS
None known as of arptables-0.0.3.3 release
.SH AUTHOR
Jochen Friedrich <jochen@scram.de>
.SH SEE ALSO
.BR arptables-legacy-restore "(8), " arptables-legacy "(8) "
